### ISSUE TITLE
KeyError thrown: If a package no longer exists on Index

### ISSUE THREAD

**Issue by harshad16** [thoth-station/package-update-job#291]
**Describe the bug**
As the job package-update, checks for updates of a package in the Index based on a version. 
The job fails, if the package is no longer available on the index. 
for example: `'https://pypi.org/simple' no longer provides 'mypy-boto3-ssmsap'`

In this case the job is throwing KeyError:
Sentry issue: [THTH-001-THOTH-1T1S](https://sentry.io/organizations/red-hat-it/issues/3682886191/?referrer=github_integration)

**Comment by KPostOffice** [comment]
Hey, this issue is actually with the Pulp indexes. They aren't returning any packages, so the code is erroring out due to a key error when looking for packages. I can fix this pretty easily with `.get("packages", [])` instead of indexing packages directly.

However, I am also wondering what's happening with the pulp indexes? Why don't they have any packages?

**Comment by harshad16** [comment]
If pulp index are the reason, then we  should change this to `https://github.com/thoth-station/package-update-job/blob/7e74f561824ecbba7e19244f83aa7695b4ba6c0c/producer.py#L184` to `get_python_package_index_all(enabled = True) ` so we only do the check for enabled index.

pulp index don't have any packages, the previous iteration of pulp index deployment seems to have not backup the packages. we can work on removing them from our list indexes completely.

one note though, based on the trace back from the sentry issue it shows:
`'https://pypi.org/simple' no longer provides 'mypy-boto3-ssmsap'`
initially, the package was 'mypy-boto3-ssmsap' , however the maintainer have change the package to  (mypy-boto3-ssm-sap)[https://pypi.org/project/mypy-boto3-ssm-sap/], is this type of cases already handled ?

**Comment by KPostOffice** [comment]
Got it. That makes sense. Let's make both changes just in case.

As for the package name changing, the package would just be marked as unavailable in the DB so that it isn't used during adviser's resolution. If there is somewhere these name changes are tracked there might be a better option, but this is what we do now.

**Comment by harshad16** [comment]
> As for the package name changing, the package would just be marked as unavailable in the DB so that it isn't used during adviser's resolution. If there is somewhere these name changes are tracked there might be a better option, but this is what we do now.

can you share where in the source code it is marked as unavailable when package-name changes ?
and maybe prescription can be a way to have this info, in this way adviser can suggest user that package has changed the name.

**Comment by KPostOffice** [comment]
- First: https://github.com/thoth-station/package-update-job/blob/7e74f561824ecbba7e19244f83aa7695b4ba6c0c/producer.py#L90
- Then: https://github.com/thoth-station/package-update-job/blob/7e74f561824ecbba7e19244f83aa7695b4ba6c0c/producer.py#L93
- Finally: https://github.com/thoth-station/investigator/blob/68c621290655da05503947f79b2d3b59de03f261/thoth/investigator/missing_package/investigate_missing_package.py#L50

**Comment by harshad16** [comment]
thanks for sharing the details.
will you work on this issue this sprint?

**Comment by KPostOffice** [comment]
Yeah, I'll add it to this sprint
